app = "donfrancisco-backend"
primary_region = "gru"

[http_service]
  auto_start_machines = true
  auto_stop_machines = true
  force_https = true
  internal_port = 8080
  # Esto asegura que si no hay visitas, no haya máquinas encendidas (costo $0)
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  # Reducido al mínimo para no generar cobros
  memory = "256mb"
